### ISSUE TITLE
When JSD plugin is "on" it's destroying page source variables 

### ISSUE THREAD

**Issue by KevinFaurholt** [benmmurphy/jsdeminifier_xpi#9]
Hello Ben,

Thanks for the js deminifier. it is truly a great contribution to the open source community and firefox! :)

However, I just discovered that when having your extension installed and "activated" it breaks the page.

Quick example. If you do the following
1. install chris pedricks javascript developer plugin (if you have not already)
2. enter: about:config in address bar
3. find javascript.options.strict and set to true + restart
4. goto http://www.volvocars.com/uk/all-cars/volvo-c70/tools/Pages/offers.aspx
5. Open Firebug
6. Look at the Net Tab and find outgoing image request to tribalfusion. if you keep reloading it keeps firing
7. then activate jsdeminifier
8. reload the page
9. Tribalfusion image requests stops working.
10. Error is thrown in error console on the page.
11. turn off jsdeminifier and everything works again.
## 

Thanks for looking into.

Cheers,
Kevin

**Comment by benmmurphy** [comment]
thanks for the bug report

unfortunately, the algorithm jsdeminifier uses is not 100% robust. it is very fast but not 100% accurate. previously I had looked at using uglifyjs to do the beautifying but it would run out of stack space. i'll have a look at it again because uglifyjs may have been improved.

**Comment by KevinFaurholt** [comment]
Closing

**Comment by KevinFaurholt** [comment]
close #9
